
name: Coverity
on:
  schedule:
    - cron: '0 5 * * *' # Daily at 05:00 UTC
  push:
    branches:
      - master
jobs:
  coverity:
    name: "Test Suite"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: welder-web
    steps:

      - name: Clone repository
        uses: actions/checkout@v2
        with:
         path: welder-web

      - name: Install Dependencies
        run: |
          sudo apt-get install nodejs npm
      - name: Download Coverity Tool
        run: |
          make coverity-download
        env:
         COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
         COVERITY_EMAIL: ${{ secrets.COVERITY_EMAIL }}

      - name: Coverity check
        run: |
          make coverity-check
      - name: Upload analysis results
        run: |
          make coverity-submit
        env:
         COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
         COVERITY_EMAIL: ${{ secrets.COVERITY_EMAIL }}
